---
- name: Install Puppet
  hosts: testserver
  gather_facts: false
  become: true
  tasks:
    - import_role:
       name: puppet_standalone
       
---
- name: install the puppet rpm from a remote repo
  apt:
    name: https://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
    state: present

- name: Set puppetlabs.repo's puppetlabs-devel section enabled to 1
  ini_file:
    path: /etc/apt.repos.d/puppetlabs.repo
    section: puppetlabs-devel
    option: enabled
    value: 1
    create: no
    backup: no

- name: Install puppet
  apt:
    name: "{{ item }}"
  with_items:
    - puppetserver
    - puppet

- name: Start puppet
  systemd:
    name: puppet
    state: started

- name: Enable puppet
  systemd:
    name: puppet
    enabled: yes
